name: golang/1.15 alpine-fuzz

on:
  push:
    branches: 
      - main
    paths:
      - Golang/1.15-alpine-fuzz/**
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/merit/golang 1.15
          tag-sha: true
          tag-edge: false
          tag-latest: true
      
         
      - 
         name: Set up QEMU
         uses: docker/setup-qemu-action@v1
     
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
       name: Login to GHCR
       uses: docker/login-action@v1
       with:
          registry: ghcr.io
          username: ${{SECRETS_USER_GITHUB}}
          password: ${{SECRETS_GITHUB_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Golang/1.15-alpine-fuzz/Dockerfile
       tags: |
        golang:<1.15-alpine-fuzz>-latest
        ghcr.io/golang:<1.15-alpine-fuzz>-latest
        
       push: ${{ github.ref == 'refs/heads/main' }}
       
