name: golang/1.17-alpine-fuzz

on:
  push:
    branches: 
      - main
    paths:
      - Golang/1.17-alpine-fuzz/**
  pull_request:
    branches: [ main ]

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Golang/1.17-alpine-fuzz/Dockerfile
